# hosts/personal-workstation/hardware-configuration.nix
# Generated by nixos-generate-config on the actual machine (Phase 2).
# Placeholder — replace with the real generated file.
{ ... }:
{
  # Run: nixos-generate-config --show-hardware-config > hardware-configuration.nix
  # Then commit the result here.
}
