# hosts/home-server/hardware-configuration.nix
# Generated by nixos-generate-config on the home server (Phase 4).
# Placeholder — replace with the real generated file.
# BEFORE WIPING PROXMOX:
#   1. Inventory all VMs/containers
#   2. Export/snapshot important VMs
#   3. Document network config (bridges, static IPs, VLANs)
{ ... }:
{
  # Run: nixos-generate-config --show-hardware-config > hardware-configuration.nix
}
