# hosts/surface/hardware-configuration.nix
# Generated by nixos-generate-config on the Surface (Phase 3).
# Placeholder — replace with the real generated file.
# PRE-INSTALL CHECKLIST:
#   1. Disable Secure Boot in Surface UEFI (Volume Up + Power → Security)
#   2. Prepare a USB keyboard (Type Cover won't work during install)
#   3. USB-C hub needed to connect USB drive + keyboard simultaneously
{ ... }:
{
  # Run: nixos-generate-config --show-hardware-config > hardware-configuration.nix
}
