# modules/hardware/missandei.nix
# Hardware configuration for Missandei (personal workstation).
# Generated by nixos-generate-config on the actual machine — do not edit manually.
# Ryzen 9 5900X, Gigabyte Aorus B550, GTX 1060, NVMe root.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/0cb62070-49f1-4e10-b903-03e9613f9c57";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/3E41-0A44";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/disk/by-partuuid/06968460-c056-4951-a111-96c01fe4e2bd";
        # Encrypt swap with a random key on every boot.
        # This prevents sensitive in-memory data from persisting on disk unencrypted.
        # Must use by-partuuid (partition table UUID) not by-uuid (filesystem UUID),
        # because randomEncryption erases the filesystem UUID on every boot.
        randomEncryption.enable = true;
      }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
